load(
    "@io_bazel_rules_rust//rust:triple_mappings.bzl",
    "triple_to_constraint_set",
)

platform(
    name = "arm-unknown_linux-gnueabi",
    constraint_values = triple_to_constraint_set("arm-unknown-linux-gnueabi"),
)
